name: 'Get Access Token For App'
description: Action that can be used to retrieve an access token for an app installation using the app's private key.
inputs:
  private_key:
    description: Private key to use to create the access token
    required: true
  app_id:
    description: ID of the app to retrieve the access token for
    required: true
  installation_id:
    description: Installation ID of the app 
    required: true
outputs:
  token:
    description: Access token that can be used with the GitHub API to perform actions on behalf of the installed app

runs:
  using: 'node12'
  main: 'dist/index.js'